### ISSUE TITLE
Administrator can not delete user

### ISSUE THREAD

**Issue by sergio-ocon** [propedeutica/lastablas#15]
The administrator can't delete last user. I don't know if that happens with others

**Comment by alexvkcr** [comment]
Going to check

**Comment by alexvkcr** [comment]
When I try to delete with Ana Frocada, who is an admin, I can't delete any user because action destroy is not implemented for Users controller

**Comment by sergio-ocon** [comment]
Can you please do the following?

Users can delete their account in the Edit tab.
1. Add a link in the home tab to the Edit tab
Create tests for administrators deleting the user account
2. Create those tests

I have the code that implements the destroy action, but I need the tests (the only complicated thing is to make sure that the user calling destroy is an admin)

**Comment by sergio-ocon** [comment]
In fact, create the code and I will compare :D

**Comment by sergio-ocon** [comment]
What is the status of this?

**Comment by alexvkcr** [comment]
Pending waiting someone to take charge, should it be addressed over PR#14 ?

**Comment by sergio-ocon** [comment]
Fixed
